/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jogo;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

public class AdicionarQuestaoTela extends javax.swing.JFrame {
    List <Pergunta> perguntasFaceis;
    List <Pergunta> perguntasMedias;
    List <Pergunta> perguntasDificeis;
    
    
    int numeroQuestaoFacil;
    int numeroQuestaoMedia;
    int numeroQuestaoDificil;
    
    public AdicionarQuestaoTela() throws Exception {
        initComponents();
        
        perguntasFaceis = new AdicionarQuestaoFacilDAO().obterTamanho();
        perguntasMedias = new AdicionarQuestaoMedioDAO().obterTamanho();
        perguntasDificeis = new AdicionarQuestaoDificilDAO().obterTamanho();
        
        numeroQuestaoFacil = perguntasFaceis.size() + 1;
        numeroQuestaoMedia = perguntasMedias.size() + 1;
        numeroQuestaoDificil = perguntasDificeis.size() + 1;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CaixaParaEmail = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCB_Dificuldade = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtEnunciado = new javax.swing.JTextField();
        BotaoAdicionarQuestao = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtAltA = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAltE = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAltB = new javax.swing.JTextField();
        txtAltC = new javax.swing.JTextField();
        txtAltD = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtRespostaCorreta = new javax.swing.JTextField();
        botaoVoltar = new javax.swing.JButton();

        CaixaParaEmail.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel1.setText("Adicionar Questão");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 290, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Dificuldade a adicionar a questão:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jCB_Dificuldade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facil", "Medio", "Dificil" }));
        getContentPane().add(jCB_Dificuldade, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 140, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel3.setText("Enunciado:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        getContentPane().add(txtEnunciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 1200, -1));

        BotaoAdicionarQuestao.setText("Adicionar Questão");
        BotaoAdicionarQuestao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoAdicionarQuestaoMouseClicked(evt);
            }
        });
        BotaoAdicionarQuestao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAdicionarQuestaoActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoAdicionarQuestao, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 650, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel4.setText("Alt A:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        getContentPane().add(txtAltA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 1250, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel5.setText("Alt B:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));
        getContentPane().add(txtAltE, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 1250, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel6.setText("Alt C:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel7.setText("Alt D:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel8.setText("Alt E:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));
        getContentPane().add(txtAltB, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 1250, -1));
        getContentPane().add(txtAltC, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 1250, -1));
        getContentPane().add(txtAltD, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 1250, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel9.setText("Resposta Correta:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, 30));
        getContentPane().add(txtRespostaCorreta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, 1130, -1));

        botaoVoltar.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\Downloads\\BotãoVoltarAzul.png")); // NOI18N
        botaoVoltar.setBorder(null);
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 100, 90));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoAdicionarQuestaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAdicionarQuestaoActionPerformed
        // TODO add your handling code here:
        String dificuldade = jCB_Dificuldade.getSelectedItem().toString();

        String letraFacil = "F";
        String letraRespostaFacil = "RF";
        
        String letraMedia = "M";
        String letraRespostaMedia = "RM";
        
        String letraDificil = "D";
        String letraRespostaDificil = "RD";
        
        String enunciado = txtEnunciado.getText();
        String respA = txtAltA.getText();
        String respB = txtAltB.getText();
        String respC = txtAltC.getText();
        String respD = txtAltD.getText();
        String respE = txtAltE.getText();
        String respCorreta = txtRespostaCorreta.getText();

        if (dificuldade == "Facil") {
            try {
                Connection conexao = ConnectionFactory.getConnection();
                Connection conexao2 = ConnectionFactory.getConnection();

                String sql = "Insert into perguntas (idPergunta, Pergunta) values (?, ?)";
                String sql2 = "Insert into respostas (idResposta, RespA, RespB, RespC, RespD, RespE, idPergunta, RespCorreta) values (?, ?, ?, ?, ?, ?, ?, ?)";

                PreparedStatement ps = conexao.prepareStatement(sql);
                PreparedStatement ps2 = conexao2.prepareStatement(sql2);

                String idPergunta = letraFacil.concat(String.valueOf(numeroQuestaoFacil));
                String idResposta = letraRespostaFacil.concat(String.valueOf(numeroQuestaoFacil));

                ps.setString(1, idPergunta);
                ps.setString(2, enunciado);

                ps2.setString(1, idResposta);
                ps2.setString(2, respA);
                ps2.setString(3, respB);
                ps2.setString(4, respC);
                ps2.setString(5, respD);
                ps2.setString(6, respE);
                ps2.setString(7, idPergunta);
                ps2.setString(8, respCorreta);

                ps.execute();
                ps2.execute();
                
                JOptionPane.showMessageDialog(null, "Questão adicionada com sucesso!!!");
                
                 txtEnunciado.setText("");
                txtAltA.setText("");
                txtAltB.setText("");
                txtAltC.setText("");
                txtAltD.setText("");
                txtAltE.setText("");
                txtRespostaCorreta.setText("");
                
                ps.close();
                ps2.close();

                conexao.close();
                conexao2.close();
                numeroQuestaoFacil++;
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
        else if (dificuldade == "Medio") {
            try {
                Connection conexao = ConnectionFactory.getConnection();
                Connection conexao2 = ConnectionFactory.getConnection();

                String sql = "Insert into perguntas (idPergunta, Pergunta) values (?, ?)";
                String sql2 = "Insert into respostas (idResposta, RespA, RespB, RespC, RespD, RespE, idPergunta, RespCorreta) values (?, ?, ?, ?, ?, ?, ?, ?)";

                PreparedStatement ps = conexao.prepareStatement(sql);
                PreparedStatement ps2 = conexao2.prepareStatement(sql2);

                String idPergunta = letraMedia.concat(String.valueOf(numeroQuestaoMedia));
                String idResposta = letraRespostaMedia.concat(String.valueOf(numeroQuestaoMedia));

                ps.setString(1, idPergunta);
                ps.setString(2, enunciado);

                ps2.setString(1, idResposta);
                ps2.setString(2, respA);
                ps2.setString(3, respB);
                ps2.setString(4, respC);
                ps2.setString(5, respD);
                ps2.setString(6, respE);
                ps2.setString(7, idPergunta);
                ps2.setString(8, respCorreta);

                ps.execute();
                ps2.execute();
                
                JOptionPane.showMessageDialog(null, "Questão adicionada com sucesso!!!");
                
                txtEnunciado.setText("");
                txtAltA.setText("");
                txtAltB.setText("");
                txtAltC.setText("");
                txtAltD.setText("");
                txtAltE.setText("");
                txtRespostaCorreta.setText("");
                
                
                txtEnunciado.setText("");
                txtAltA.setText("");
                txtAltB.setText("");
                txtAltC.setText("");
                txtAltD.setText("");
                txtAltE.setText("");
                txtRespostaCorreta.setText("");
            
                ps.close();
                ps2.close();

                conexao.close();
                conexao2.close();
                numeroQuestaoMedia++;
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
        else {
            try {
                Connection conexao = ConnectionFactory.getConnection();
                Connection conexao2 = ConnectionFactory.getConnection();

                String sql = "Insert into perguntas (idPergunta, Pergunta) values (?, ?)";
                String sql2 = "Insert into respostas (idResposta, RespA, RespB, RespC, RespD, RespE, idPergunta, RespCorreta) values (?, ?, ?, ?, ?, ?, ?, ?)";

                PreparedStatement ps = conexao.prepareStatement(sql);
                PreparedStatement ps2 = conexao2.prepareStatement(sql2);

                String idPergunta = letraDificil.concat(String.valueOf(numeroQuestaoDificil));
                String idResposta = letraRespostaDificil.concat(String.valueOf(numeroQuestaoDificil));

                ps.setString(1, idPergunta);
                ps.setString(2, enunciado);

                ps2.setString(1, idResposta);
                ps2.setString(2, respA);
                ps2.setString(3, respB);
                ps2.setString(4, respC);
                ps2.setString(5, respD);
                ps2.setString(6, respE);
                ps2.setString(7, idPergunta);
                ps2.setString(8, respCorreta);

                ps.execute();
                ps2.execute();
                
                JOptionPane.showMessageDialog(null, "Questão adicionada com sucesso!!!");
                        
                txtEnunciado.setText("");
                txtAltA.setText("");
                txtAltB.setText("");
                txtAltC.setText("");
                txtAltD.setText("");
                txtAltE.setText("");
                txtRespostaCorreta.setText("");
                
                ps.close();
                ps2.close();

                conexao.close();
                conexao2.close();
                numeroQuestaoDificil++;
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_BotaoAdicionarQuestaoActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        // TODO add your handling code here:
        AlterarQuestionarioTela Mqt = new AlterarQuestionarioTela();
        Mqt.setVisible(true);
        
        String pegarEmail = CaixaParaEmail.getText();
        AlterarQuestionarioTela.CaixaParaEmail.setText(pegarEmail);
        
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void BotaoAdicionarQuestaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoAdicionarQuestaoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BotaoAdicionarQuestaoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarQuestaoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarQuestaoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarQuestaoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarQuestaoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AdicionarQuestaoTela().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(AdicionarQuestaoTela.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAdicionarQuestao;
    public static javax.swing.JLabel CaixaParaEmail;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JComboBox<String> jCB_Dificuldade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAltA;
    private javax.swing.JTextField txtAltB;
    private javax.swing.JTextField txtAltC;
    private javax.swing.JTextField txtAltD;
    private javax.swing.JTextField txtAltE;
    private javax.swing.JTextField txtEnunciado;
    private javax.swing.JTextField txtRespostaCorreta;
    // End of variables declaration//GEN-END:variables
}
