/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jogo;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author cadub
 */
public class DeletarQuestaoTela extends javax.swing.JFrame {

    /**
     * Creates new form DeletarQuestaoTela
     */
    public DeletarQuestaoTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CaixaParaEmail = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtIdQuestao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botaoBuscarQuestao = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtEnunciado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAltA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAltE = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtAltB = new javax.swing.JTextField();
        txtAltC = new javax.swing.JTextField();
        txtAltD = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtRespostaCorreta = new javax.swing.JTextField();
        botaoDeletarQuestao = new javax.swing.JButton();

        CaixaParaEmail.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel1.setText("Deletar Questão");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 250, -1));

        botaoVoltar.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\Downloads\\BotãoVoltarAzul.png")); // NOI18N
        botaoVoltar.setBorder(null);
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 80, 80));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Qual questão você quer deletar?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));
        getContentPane().add(txtIdQuestao, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 180, -1));

        jLabel4.setText("Obs: Para selecionar a questão digite a letra que corresponde a dificuldade dela.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, -1, 20));

        jLabel5.setText("Ex: \"F1\", ..., \"M1\", ..., \"D1\" ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 170, -1, -1));

        botaoBuscarQuestao.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\Downloads\\IconeLupa.png")); // NOI18N
        botaoBuscarQuestao.setText("Buscar");
        botaoBuscarQuestao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarQuestaoActionPerformed(evt);
            }
        });
        getContentPane().add(botaoBuscarQuestao, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel6.setText("Enunciado:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        getContentPane().add(txtEnunciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 1200, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel7.setText("Alt A:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        txtAltA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAltAActionPerformed(evt);
            }
        });
        getContentPane().add(txtAltA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 1250, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel8.setText("Alt B:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));
        getContentPane().add(txtAltE, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 1250, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel9.setText("Alt C:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel10.setText("Alt D:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel11.setText("Alt E:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));
        getContentPane().add(txtAltB, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 1250, -1));
        getContentPane().add(txtAltC, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 1250, -1));
        getContentPane().add(txtAltD, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 1250, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel12.setText("Resposta Correta:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, 30));
        getContentPane().add(txtRespostaCorreta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 550, 1130, -1));

        botaoDeletarQuestao.setText("Deletar Questão");
        botaoDeletarQuestao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeletarQuestaoActionPerformed(evt);
            }
        });
        getContentPane().add(botaoDeletarQuestao, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 640, -1, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoBuscarQuestaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarQuestaoActionPerformed
        // TODO add your handling code here:
        String idQuestao = txtIdQuestao.getText();
        txtIdQuestao.setEnabled(false);
        try {
            Connection conexao = ConnectionFactory.getConnection();
            String sql = "Select perguntas.idPergunta, Pergunta, RespA, RespB, RespC, RespD, RespE, RespCorreta from perguntas inner JOIN respostas on perguntas.idPergunta = respostas.idPergunta where perguntas.idPergunta = ?";

            PreparedStatement ps = conexao.prepareStatement(sql);

            ps.setString(1, idQuestao);

            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                txtEnunciado.setText(rs.getString(2));
                txtAltA.setText(rs.getString(3));
                txtAltB.setText(rs.getString(4));
                txtAltC.setText(rs.getString(5));
                txtAltD.setText(rs.getString(6));
                txtAltE.setText(rs.getString(7));
                txtRespostaCorreta.setText(rs.getString(8));
            }
            else {
                JOptionPane.showMessageDialog(null, "Essa questão não existe!!!");
                txtIdQuestao.setEnabled(true);
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível encontrar a questão.");
            txtIdQuestao.setEnabled(true);
        }

    }//GEN-LAST:event_botaoBuscarQuestaoActionPerformed

    private void botaoDeletarQuestaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeletarQuestaoActionPerformed
        // TODO add your handling code here:
        String idQuestao = txtIdQuestao.getText();
 
        try {
            Connection conexao = ConnectionFactory.getConnection();
            Connection conexao2 = ConnectionFactory.getConnection();

            String sql = "Delete from respostas where idPergunta = ?"; 
            String sql2 = "Delete from perguntas where idPergunta = ?";

            PreparedStatement ps = conexao.prepareStatement(sql);
            PreparedStatement ps2 = conexao2.prepareStatement(sql2);

            ps.setString(1, idQuestao);
            ps2.setString(1, idQuestao);

            ps.execute();
            ps2.execute();

            JOptionPane.showMessageDialog(null, "Questão deletada com sucesso!!!");

            txtEnunciado.setText("");
            txtAltA.setText("");
            txtAltB.setText("");
            txtAltC.setText("");
            txtAltD.setText("");
            txtAltE.setText("");
            txtRespostaCorreta.setText("");

            txtIdQuestao.setEnabled(true);

            ps.close();
            ps2.close();
            conexao.close();
            conexao2.close();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível deletar a questão");
        }
    }//GEN-LAST:event_botaoDeletarQuestaoActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        // TODO add your handling code here:
        AlterarQuestionarioTela Mqt = new AlterarQuestionarioTela();
        Mqt.setVisible(true);
        
        String pegarEmail = CaixaParaEmail.getText();
        AlterarQuestionarioTela.CaixaParaEmail.setText(pegarEmail);
        
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void txtAltAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAltAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeletarQuestaoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeletarQuestaoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeletarQuestaoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeletarQuestaoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeletarQuestaoTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel CaixaParaEmail;
    private javax.swing.JButton botaoBuscarQuestao;
    private javax.swing.JButton botaoDeletarQuestao;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAltA;
    private javax.swing.JTextField txtAltB;
    private javax.swing.JTextField txtAltC;
    private javax.swing.JTextField txtAltD;
    private javax.swing.JTextField txtAltE;
    private javax.swing.JTextField txtEnunciado;
    private javax.swing.JTextField txtIdQuestao;
    private javax.swing.JTextField txtRespostaCorreta;
    // End of variables declaration//GEN-END:variables
}
