/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jogo;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author cadub
 */
public class DificuldadeTela extends javax.swing.JFrame {

    /**
     * Creates new form DificuldadeTela
     */
    public DificuldadeTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CaixaParaEmail = new javax.swing.JLabel();
        BotãoDificuldadeFácil = new javax.swing.JButton();
        BotãoDificuldadeMédio = new javax.swing.JButton();
        BotãoDificuldadeDifícil = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Fundo = new javax.swing.JLabel();

        CaixaParaEmail.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotãoDificuldadeFácil.setBackground(new java.awt.Color(242, 168, 84));
        BotãoDificuldadeFácil.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\Downloads\\BotãoDificuldadeFácil.png")); // NOI18N
        BotãoDificuldadeFácil.setBorder(null);
        BotãoDificuldadeFácil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoDificuldadeFácilActionPerformed(evt);
            }
        });
        getContentPane().add(BotãoDificuldadeFácil, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 170, 150));

        BotãoDificuldadeMédio.setBackground(new java.awt.Color(242, 168, 84));
        BotãoDificuldadeMédio.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\Downloads\\BotãoDificuldadeMédia.png")); // NOI18N
        BotãoDificuldadeMédio.setBorder(null);
        BotãoDificuldadeMédio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoDificuldadeMédioActionPerformed(evt);
            }
        });
        getContentPane().add(BotãoDificuldadeMédio, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 340, 170, 150));

        BotãoDificuldadeDifícil.setBackground(new java.awt.Color(242, 168, 84));
        BotãoDificuldadeDifícil.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\Downloads\\BotãoDificuldadeDifícil.png")); // NOI18N
        BotãoDificuldadeDifícil.setBorder(null);
        BotãoDificuldadeDifícil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoDificuldadeDifícilActionPerformed(evt);
            }
        });
        getContentPane().add(BotãoDificuldadeDifícil, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 340, 160, 150));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\Downloads\\BotãoVoltarAzul.png")); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 90));

        Fundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\Downloads\\1253QUANTUMVM.UNRARMETRO_ckbnxvahp5f44!App\\Extracted\\Imagens feitas\\Dificulddades.png")); // NOI18N
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotãoDificuldadeFácilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoDificuldadeFácilActionPerformed
        try {
            // TODO add your handling code here:
            DificuldadeFacilTela TDC = new DificuldadeFacilTela();
            TDC.setVisible(true);
            
            String pegarEmail = CaixaParaEmail.getText();
            DificuldadeFacilTela.CaixaParaEmail.setText(pegarEmail);
            
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(DificuldadeTela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotãoDificuldadeFácilActionPerformed

    private void BotãoDificuldadeMédioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoDificuldadeMédioActionPerformed
        try {
            // TODO add your handling code here:
            DificuldadeMedioTela DMT = new DificuldadeMedioTela();
            DMT.setVisible(true);
            
            String pegarEmail = CaixaParaEmail.getText();
            DificuldadeMedioTela.CaixaParaEmail.setText(pegarEmail);
            
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(DificuldadeTela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotãoDificuldadeMédioActionPerformed

    private void BotãoDificuldadeDifícilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoDificuldadeDifícilActionPerformed
        try {
            // TODO add your handling code here:
            DificuldadeDificilTela DDT = new DificuldadeDificilTela();
            DDT.setVisible(true);
            
            String pegarEmail = CaixaParaEmail.getText();
            DificuldadeDificilTela.CaixaParaEmail.setText(pegarEmail);
            
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(DificuldadeTela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotãoDificuldadeDifícilActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        PrincipalTela Pt = new PrincipalTela();
        Pt.setVisible(true);
        
        String pegarEmail = CaixaParaEmail.getText();
        PrincipalTela.CaixaParaEmail.setText(pegarEmail);
        
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DificuldadeTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DificuldadeTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DificuldadeTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DificuldadeTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DificuldadeTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotãoDificuldadeDifícil;
    private javax.swing.JButton BotãoDificuldadeFácil;
    private javax.swing.JButton BotãoDificuldadeMédio;
    public static javax.swing.JLabel CaixaParaEmail;
    private javax.swing.JLabel Fundo;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
