/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jogo;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author cadub
 */
public class DificuldadeDificilTela extends javax.swing.JFrame {
    List <Pergunta> perguntasDificeis;
    /**
     * Creates new form DificuldadeDificilTela
     */
    public DificuldadeDificilTela() throws Exception {
        initComponents();
        
        perguntasDificeis = new QuestoesDAODificil().obterPerguntas();
        quantidadeQuestoes.setText(String.valueOf(perguntasDificeis.size()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CaixaParaEmail = new javax.swing.JLabel();
        BotaoStart = new javax.swing.JButton();
        quantidadeQuestoes = new javax.swing.JLabel();
        BotãoVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        CaixaParaEmail.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotaoStart.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\Downloads\\StartDificudadeDifícil.png")); // NOI18N
        BotaoStart.setBorder(null);
        BotaoStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoStartMouseClicked(evt);
            }
        });
        BotaoStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoStartActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 570, 320, 80));

        quantidadeQuestoes.setFont(new java.awt.Font("Eras Bold ITC", 0, 22)); // NOI18N
        quantidadeQuestoes.setForeground(new java.awt.Color(255, 255, 255));
        quantidadeQuestoes.setText("17");
        getContentPane().add(quantidadeQuestoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 80, -1));

        BotãoVoltar.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\Downloads\\BotãoVoltarNether.png")); // NOI18N
        BotãoVoltar.setBorder(null);
        BotãoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(BotãoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 110));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\Downloads\\FundoEscuro.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, -1, -1));

        fundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\Downloads\\1253QUANTUMVM.UNRARMETRO_ckbnxvahp5f44!App\\Extracted\\Imagens feitas\\Dificil.png")); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoStartMouseClicked
        // TODO add your handling code her
    }//GEN-LAST:event_BotaoStartMouseClicked

    private void BotaoStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoStartActionPerformed
        // TODO add your handling code here:
        QuestoesDificeisTela QDT;
        try {
            QDT = new QuestoesDificeisTela();
            QDT.setVisible(true);
            
            String pegarEmail = CaixaParaEmail.getText();
            QuestoesDificeisTela.CaixaParaEmail.setText(pegarEmail);
        } catch (Exception ex) {
            Logger.getLogger(DificuldadeDificilTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.dispose();
    }//GEN-LAST:event_BotaoStartActionPerformed

    private void BotãoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoVoltarActionPerformed
        // TODO add your handling code here:
        DificuldadeTela Dt = new DificuldadeTela();
        Dt.setVisible(true);

        String pegarEmail = CaixaParaEmail.getText();
        DificuldadeTela.CaixaParaEmail.setText(pegarEmail);

        this.dispose();
    }//GEN-LAST:event_BotãoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DificuldadeDificilTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DificuldadeDificilTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DificuldadeDificilTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DificuldadeDificilTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DificuldadeDificilTela().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(DificuldadeDificilTela.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoStart;
    private javax.swing.JButton BotãoVoltar;
    public static javax.swing.JLabel CaixaParaEmail;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel quantidadeQuestoes;
    // End of variables declaration//GEN-END:variables
}
