/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jogo;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author cadub
 */
public class DificuldadeFacilTela extends javax.swing.JFrame {
    List <Pergunta> perguntasFaceis;
    /**
     * Creates new form DificuldadeFacilTela
     */
    public DificuldadeFacilTela() throws Exception {
        initComponents();
        
        perguntasFaceis= new QuestoesDAOFacil().obterPerguntas();
        quantidadeQuestoes.setText(String.valueOf(perguntasFaceis.size()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CaixaParaEmail = new javax.swing.JLabel();
        StartFacil = new javax.swing.JButton();
        BotaoVoltar = new javax.swing.JButton();
        quantidadeQuestoes = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        CaixaParaEmail.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StartFacil.setBackground(new java.awt.Color(137, 173, 119));
        StartFacil.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\Downloads\\BotãoStartFácil.png")); // NOI18N
        StartFacil.setBorder(null);
        StartFacil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StartFacilMouseClicked(evt);
            }
        });
        StartFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartFacilActionPerformed(evt);
            }
        });
        getContentPane().add(StartFacil, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 570, 320, 80));

        BotaoVoltar.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\Downloads\\BotãoVoltar2.png")); // NOI18N
        BotaoVoltar.setBorder(null);
        BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 90));

        quantidadeQuestoes.setFont(new java.awt.Font("Eras Bold ITC", 0, 22)); // NOI18N
        quantidadeQuestoes.setForeground(new java.awt.Color(255, 255, 255));
        quantidadeQuestoes.setText("5");
        getContentPane().add(quantidadeQuestoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 160, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\Downloads\\FundoRosa.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 20, 40));

        Fundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\Downloads\\1253QUANTUMVM.UNRARMETRO_ckbnxvahp5f44!App\\Extracted\\Imagens feitas\\Facil.png")); // NOI18N
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void StartFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartFacilActionPerformed
        // TODO add your handling code here:
        QuestoesFaceisTela QFT;
        try {
            QFT = new QuestoesFaceisTela();
            QFT.setVisible(true);
            
            String pegarEmail = CaixaParaEmail.getText();
            QuestoesFaceisTela.CaixaParaEmail.setText(pegarEmail);
        } catch (Exception ex) {
            Logger.getLogger(DificuldadeFacilTela.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.dispose();
    }//GEN-LAST:event_StartFacilActionPerformed

    private void StartFacilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartFacilMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_StartFacilMouseClicked

    private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVoltarActionPerformed
        // TODO add your handling code here:
        DificuldadeTela Dt = new DificuldadeTela();
        Dt.setVisible(true);
        
        String pegarEmail = CaixaParaEmail.getText();
        DificuldadeTela.CaixaParaEmail.setText(pegarEmail);
        
        this.dispose();
    }//GEN-LAST:event_BotaoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DificuldadeFacilTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DificuldadeFacilTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DificuldadeFacilTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DificuldadeFacilTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DificuldadeFacilTela().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(DificuldadeFacilTela.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoVoltar;
    public static javax.swing.JLabel CaixaParaEmail;
    private javax.swing.JLabel Fundo;
    public static javax.swing.JButton StartFacil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel quantidadeQuestoes;
    // End of variables declaration//GEN-END:variables
}
