/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jogo;

import org.apache.commons.mail.DefaultAuthenticator;
import org.apache.commons.mail.SimpleEmail;
import java.util.Random;
import javax.swing.JOptionPane;

public class InserirCodigoTela extends javax.swing.JFrame {
    Random random = new Random();
    int codigo = random.nextInt((99999 - 10000 + 1) + 10000);
    
    /**
     * Creates new form InserirCodigoTela
     */
    public InserirCodigoTela() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CaixaParaEmail = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        labelCodigo = new javax.swing.JLabel();
        botaoConfirmarCodigo = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        botaoMandarCodigo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        CaixaParaEmail.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Verificar Email");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ao clicar no botão \"Mandar Código\", um código será enviado ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 570, 30));

        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("para seu e-mail. Escreva-o na caixa abaixo. Depois clique no botão ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        txtCodigo.setForeground(new java.awt.Color(0, 0, 0));
        txtCodigo.setCaretColor(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 270, 30));

        labelCodigo.setFont(new java.awt.Font("Eras Bold ITC", 0, 20)); // NOI18N
        labelCodigo.setForeground(new java.awt.Color(255, 255, 255));
        labelCodigo.setText("Código:");
        getContentPane().add(labelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        botaoConfirmarCodigo.setText("Confirmar Código");
        botaoConfirmarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(botaoConfirmarCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, -1, -1));

        botaoVoltar.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\Downloads\\BotãoVoltarAzul.png")); // NOI18N
        botaoVoltar.setBorder(null);
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 70, 70));

        botaoMandarCodigo.setText("Mandar Código");
        botaoMandarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMandarCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(botaoMandarCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        jLabel4.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("\"Confirmar Código\".");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        Fundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\Downloads\\FundoVerificarCodigo.png")); // NOI18N
        Fundo.setText("jLabel5");
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       
      
    }//GEN-LAST:event_formWindowOpened

    private void botaoConfirmarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarCodigoActionPerformed
        // TODO add your handling code here:
        String codigo1 = txtCodigo.getText();
        
        if (codigo1.equals(String.valueOf(codigo))) {
            TrocarSenhaTela.txtSenha.setEnabled(true);
            TrocarSenhaTela.txtConfirmarSenha.setEnabled(true);
            TrocarSenhaTela.BotaoMudarSenha.setEnabled(true);
            TrocarSenhaTela.txtEmail.setEnabled(false);
            TrocarSenhaTela.BotaoVerificar.setEnabled(false);
            
            this.dispose();
        }
        else {
            JOptionPane.showMessageDialog(null, "Código incorreto");
        }
    }//GEN-LAST:event_botaoConfirmarCodigoActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        // TODO add your handling code here:
        TrocarSenhaTela.txtEmail.setText("");
        
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoMandarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMandarCodigoActionPerformed
        // TODO add your handling code here:
        String pegarEmail = CaixaParaEmail.getText();
       txtCodigo.setEnabled(true);
       
       String meuEmail = "cadubas1@gmail.com";
       String minhaSenha = "rwksvesnbnapyxsa";
       
       SimpleEmail email = new SimpleEmail();
       email.setHostName("smtp.gmail.com");
       email.setSmtpPort(465);
       email.setAuthenticator(new DefaultAuthenticator(meuEmail, minhaSenha));
       email.setSSLOnConnect(true);
        
        try {
           //De onde ele está vindo
           email.setFrom(meuEmail);
           //Tema do email
           email.setSubject("Código de verificação do email");
           //Mensagem do email
           email.setMsg("O seu código é: " + codigo);
           //Destinatário do email
           email.addTo(pegarEmail);
           //Enviar Email
           email.send();
           
           JOptionPane.showMessageDialog(null, "Código Enviado");
        }
        catch (Exception e) {
           e.printStackTrace();
        }
    }//GEN-LAST:event_botaoMandarCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InserirCodigoTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel CaixaParaEmail;
    private javax.swing.JLabel Fundo;
    private javax.swing.JButton botaoConfirmarCodigo;
    private javax.swing.JButton botaoMandarCodigo;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
