/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Jogo;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cadub
 */
public class PrincipalTela extends javax.swing.JFrame {

    /** Creates new form PrincipalTela */
    public PrincipalTela() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CaixaParaEmail = new javax.swing.JLabel();
        BotaoComecar = new javax.swing.JButton();
        BotaoLogout = new javax.swing.JButton();
        BotaoHistorico = new javax.swing.JButton();
        botaoAlterarQuestionario = new javax.swing.JButton();
        Fundo = new javax.swing.JLabel();

        CaixaParaEmail.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotaoComecar.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\Downloads\\BotãoComeçar.png")); // NOI18N
        BotaoComecar.setBorder(null);
        BotaoComecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoComecarActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoComecar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 270, -1, 80));

        BotaoLogout.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\Downloads\\BotãoLogout.png")); // NOI18N
        BotaoLogout.setBorder(null);
        BotaoLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 630, 80, 80));

        BotaoHistorico.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\Downloads\\BotãoRanking.png")); // NOI18N
        BotaoHistorico.setBorder(null);
        BotaoHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoHistoricoActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 420, 310, 70));

        botaoAlterarQuestionario.setText("Alterar Questionário");
        botaoAlterarQuestionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarQuestionarioActionPerformed(evt);
            }
        });
        getContentPane().add(botaoAlterarQuestionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 560, 180, -1));

        Fundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\Downloads\\1253QUANTUMVM.UNRARMETRO_ckbnxvahp5f44!App\\Extracted\\Imagens feitas\\Começo.png")); // NOI18N
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoHistoricoActionPerformed
        // TODO add your handling code here:
        RankingTela Rt = new RankingTela();
        Rt.setVisible(true);
        
        String pegarEmail = CaixaParaEmail.getText();
        RankingTela.CaixaParaEmail.setText(pegarEmail);
        
       this.dispose();
    }//GEN-LAST:event_BotaoHistoricoActionPerformed

    private void BotaoComecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoComecarActionPerformed
        // TODO add your handling code here:
        DificuldadeTela Td = new DificuldadeTela();
        Td.setVisible(true);
        
        String pegarEmail = CaixaParaEmail.getText();
        DificuldadeTela.CaixaParaEmail.setText(pegarEmail);
        
        this.dispose();
    }//GEN-LAST:event_BotaoComecarActionPerformed

    private void BotaoLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLogoutActionPerformed
        // TODO add your handling code here:
        LoginTela Lt = new LoginTela();
        Lt.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_BotaoLogoutActionPerformed

    private void botaoAlterarQuestionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarQuestionarioActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            AlterarQuestionarioTela Mqt = new AlterarQuestionarioTela();
            Mqt.setVisible(true);
            
            String pegarEmail = CaixaParaEmail.getText();
            AlterarQuestionarioTela.CaixaParaEmail.setText(pegarEmail);
            
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(AlterarQuestionarioTela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoAlterarQuestionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoComecar;
    private javax.swing.JButton BotaoHistorico;
    private javax.swing.JButton BotaoLogout;
    public static javax.swing.JLabel CaixaParaEmail;
    private javax.swing.JLabel Fundo;
    private javax.swing.JButton botaoAlterarQuestionario;
    // End of variables declaration//GEN-END:variables

}
