/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jogo;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author cadub
 */
public class ResultadoDificilTela extends javax.swing.JFrame {

    /**
     * Creates new form ResultadoDificilTela
     */
    public ResultadoDificilTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CaixaParaEmail = new javax.swing.JLabel();
        txtPontuacao = new javax.swing.JLabel();
        txtTempo = new javax.swing.JLabel();
        txtTempoSegundos = new javax.swing.JLabel();
        txtConclusao = new javax.swing.JLabel();
        BotaoHistorico = new javax.swing.JButton();
        BotaoReiniciarQuiz = new javax.swing.JButton();
        BotaoTrocarDificuldade = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        CaixaParaEmail.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPontuacao.setFont(new java.awt.Font("Eras Bold ITC", 1, 28)); // NOI18N
        txtPontuacao.setForeground(new java.awt.Color(255, 255, 255));
        txtPontuacao.setText("jLabel1");
        getContentPane().add(txtPontuacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 430, 30));

        txtTempo.setFont(new java.awt.Font("Eras Bold ITC", 1, 28)); // NOI18N
        txtTempo.setForeground(new java.awt.Color(255, 255, 255));
        txtTempo.setText("Seu tempo: 3");
        getContentPane().add(txtTempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 246, 30));

        txtTempoSegundos.setFont(new java.awt.Font("Eras Bold ITC", 1, 28)); // NOI18N
        txtTempoSegundos.setForeground(new java.awt.Color(255, 255, 255));
        txtTempoSegundos.setText(":00");
        getContentPane().add(txtTempoSegundos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 363, 160, 40));

        txtConclusao.setFont(new java.awt.Font("Eras Bold ITC", 1, 32)); // NOI18N
        txtConclusao.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtConclusao, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 670, 70));

        BotaoHistorico.setBackground(new java.awt.Color(94, 83, 239));
        BotaoHistorico.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\Downloads\\BotãoRanking.png")); // NOI18N
        BotaoHistorico.setBorder(null);
        BotaoHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoHistoricoActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 410, 340, 100));

        BotaoReiniciarQuiz.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\Downloads\\BotãoReinicarQuizDificil.png")); // NOI18N
        BotaoReiniciarQuiz.setBorder(null);
        BotaoReiniciarQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoReiniciarQuizActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoReiniciarQuiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, 340, 100));

        BotaoTrocarDificuldade.setBackground(new java.awt.Color(94, 83, 239));
        BotaoTrocarDificuldade.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\Downloads\\BotãoTrocarDificuldade.png")); // NOI18N
        BotaoTrocarDificuldade.setBorder(null);
        BotaoTrocarDificuldade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoTrocarDificuldadeActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoTrocarDificuldade, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 270, 340, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\Downloads\\1253QUANTUMVM.UNRARMETRO_ckbnxvahp5f44!App\\Extracted\\Final_Dificil.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoHistoricoActionPerformed
        // TODO add your handling code here:
        RankingTela Th = new RankingTela();
        Th.setVisible(true);

        String pegarEmail = CaixaParaEmail.getText();
        RankingTela.CaixaParaEmail.setText(pegarEmail);

        this.dispose();
    }//GEN-LAST:event_BotaoHistoricoActionPerformed

    private void BotaoTrocarDificuldadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoTrocarDificuldadeActionPerformed
        // TODO add your handling code here:
        DificuldadeTela Td = new DificuldadeTela();
        Td.setVisible(true);

        String pegarEmail = CaixaParaEmail.getText();
        DificuldadeTela.CaixaParaEmail.setText(pegarEmail);

        this.dispose();
    }//GEN-LAST:event_BotaoTrocarDificuldadeActionPerformed

    private void BotaoReiniciarQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoReiniciarQuizActionPerformed
        // TODO add your handling code here:
        QuestoesDificeisTela Qd;
        try {
            Qd = new QuestoesDificeisTela();
            Qd.setVisible(true);
            
            String pegarEmail = CaixaParaEmail.getText();
            QuestoesDificeisTela.CaixaParaEmail.setText(pegarEmail);
        } catch (Exception ex) {
            Logger.getLogger(ResultadoDificilTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        

        this.dispose();
    }//GEN-LAST:event_BotaoReiniciarQuizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultadoDificilTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultadoDificilTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultadoDificilTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultadoDificilTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultadoDificilTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoHistorico;
    private javax.swing.JButton BotaoReiniciarQuiz;
    private javax.swing.JButton BotaoTrocarDificuldade;
    public static javax.swing.JLabel CaixaParaEmail;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel txtConclusao;
    public static javax.swing.JLabel txtPontuacao;
    public static javax.swing.JLabel txtTempo;
    public static javax.swing.JLabel txtTempoSegundos;
    // End of variables declaration//GEN-END:variables
}
