/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cadub
 */
public class ResultadoDificilTela extends javax.swing.JFrame {
    
    /**
     * Creates new form TelaResultadoDificil
     */
    public ResultadoDificilTela() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomeDificuldade = new javax.swing.JLabel();
        PegarPontuacao = new javax.swing.JLabel();
        PegarMinuto = new javax.swing.JLabel();
        PegarSegundo = new javax.swing.JLabel();
        CaixaParaEmail = new javax.swing.JLabel();
        txtPontuacao = new javax.swing.JLabel();
        txtTempo = new javax.swing.JLabel();
        txtTempoSegundos = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LogoDiscite = new javax.swing.JLabel();
        TermoDiscite = new javax.swing.JLabel();
        BotaoLogout = new javax.swing.JButton();
        BotaoHistorico = new javax.swing.JButton();
        BotaoTrocarDificuldade = new javax.swing.JButton();
        txtConclusao = new javax.swing.JLabel();
        BotaoReiniciarQuiz = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        NomeDificuldade.setText("Difícil");

        PegarPontuacao.setText("jLabel2");

        PegarMinuto.setText("jLabel2");

        PegarSegundo.setText("jLabel2");

        CaixaParaEmail.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPontuacao.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        txtPontuacao.setForeground(new java.awt.Color(255, 255, 255));
        txtPontuacao.setText("jLabel1");
        getContentPane().add(txtPontuacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 440, -1));

        txtTempo.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        txtTempo.setForeground(new java.awt.Color(255, 255, 255));
        txtTempo.setText("Seu tempo: 3");
        getContentPane().add(txtTempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 200, 260, -1));

        txtTempoSegundos.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        txtTempoSegundos.setForeground(new java.awt.Color(255, 255, 255));
        txtTempoSegundos.setText(":00");
        getContentPane().add(txtTempoSegundos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 170, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoDiscite.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\Downloads\\Icone Laranja Discite (2) (1).png")); // NOI18N
        jPanel1.add(LogoDiscite, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        TermoDiscite.setFont(new java.awt.Font("MV Boli", 0, 30)); // NOI18N
        TermoDiscite.setForeground(new java.awt.Color(255, 102, 0));
        TermoDiscite.setText("iscite");
        jPanel1.add(TermoDiscite, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 80, -1));

        BotaoLogout.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\OneDrive\\Imagens\\Saved Pictures\\IconeLogout.png")); // NOI18N
        BotaoLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BotaoLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(BotaoLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 110, 40));

        BotaoHistorico.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\OneDrive\\Imagens\\Saved Pictures\\IconeHistórico.png")); // NOI18N
        BotaoHistorico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BotaoHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoHistoricoActionPerformed(evt);
            }
        });
        jPanel1.add(BotaoHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 250, 60));

        BotaoTrocarDificuldade.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\OneDrive\\Imagens\\Saved Pictures\\Botão Trocar Dificuldade.png")); // NOI18N
        BotaoTrocarDificuldade.setBorder(null);
        BotaoTrocarDificuldade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoTrocarDificuldadeActionPerformed(evt);
            }
        });
        jPanel1.add(BotaoTrocarDificuldade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 260, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 0, 300, 410));

        txtConclusao.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        txtConclusao.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtConclusao, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 550, 51));

        BotaoReiniciarQuiz.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\OneDrive\\Imagens\\Saved Pictures\\Botão Reiniciar Quiz.png")); // NOI18N
        BotaoReiniciarQuiz.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), new javax.swing.border.MatteBorder(null)));
        BotaoReiniciarQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoReiniciarQuizActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoReiniciarQuiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 250, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\cadub\\OneDrive\\Imagens\\Saved Pictures\\Azul Laranja.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLogoutActionPerformed
        // TODO add your handling code here:
        LoginTela Lt = new LoginTela();
        Lt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoLogoutActionPerformed

    private void BotaoHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoHistoricoActionPerformed
        // TODO add your handling code here:
        HistoricoTela Th = new HistoricoTela();
        Th.setVisible(true);

        String pegarEmail = CaixaParaEmail.getText();
        HistoricoTela.CaixaParaEmail.setText(pegarEmail);

        this.dispose();
    }//GEN-LAST:event_BotaoHistoricoActionPerformed

    private void BotaoTrocarDificuldadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoTrocarDificuldadeActionPerformed
        // TODO add your handling code here:
        DificuldadeTela Td = new DificuldadeTela();
        Td.setVisible(true);

        String pegarEmail = CaixaParaEmail.getText();
        DificuldadeTela.CaixaParaEmail.setText(pegarEmail);

        this.dispose();
    }//GEN-LAST:event_BotaoTrocarDificuldadeActionPerformed

    private void BotaoReiniciarQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoReiniciarQuizActionPerformed
        // TODO add your handling code here:
        QuestoesDificeisTela Qd = new QuestoesDificeisTela();
        Qd.setVisible(true);

        String pegarEmail = CaixaParaEmail.getText();
        QuestoesDificeisTela.CaixaParaEmail.setText(pegarEmail);

        this.dispose();
    }//GEN-LAST:event_BotaoReiniciarQuizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultadoDificilTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultadoDificilTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultadoDificilTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultadoDificilTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultadoDificilTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoHistorico;
    private javax.swing.JButton BotaoLogout;
    private javax.swing.JButton BotaoReiniciarQuiz;
    private javax.swing.JButton BotaoTrocarDificuldade;
    public static javax.swing.JLabel CaixaParaEmail;
    private javax.swing.JLabel LogoDiscite;
    private javax.swing.JLabel NomeDificuldade;
    public static javax.swing.JLabel PegarMinuto;
    public static javax.swing.JLabel PegarPontuacao;
    public static javax.swing.JLabel PegarSegundo;
    private javax.swing.JLabel TermoDiscite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel txtConclusao;
    public static javax.swing.JLabel txtPontuacao;
    public static javax.swing.JLabel txtTempo;
    public static javax.swing.JLabel txtTempoSegundos;
    // End of variables declaration//GEN-END:variables
}
